//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeAgent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translatable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translatable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeAgent.Translatable", typeof(Translatable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string ButtonLock {
            get {
                return ResourceManager.GetString("ButtonLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string ButtonUnlock {
            get {
                return ResourceManager.GetString("ButtonUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pageant is already running. KeeAgent plugin will not be loaded..
        /// </summary>
        internal static string ErrPageantRunning {
            get {
                return ResourceManager.GetString("ErrPageantRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading key from entry &apos;{0}&apos; in group &apos;{1}&apos; in database &apos;{2}&apos;.
        /// </summary>
        internal static string ErrParsingKey {
            get {
                return ResourceManager.GetString("ErrParsingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &apos;{0}&apos; occured while parsing file &apos;{1}&apos;.
        /// </summary>
        internal static string ErrPpkFileException {
            get {
                return ResourceManager.GetString("ErrPpkFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string ErrUnknown {
            get {
                return ResourceManager.GetString("ErrUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Global confirm enabled*.
        /// </summary>
        internal static string GlobalConfirmEnabled {
            get {
                return ResourceManager.GetString("GlobalConfirmEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeeAgent.
        /// </summary>
        internal static string KeeAgent {
            get {
                return ResourceManager.GetString("KeeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage SSH Keys.
        /// </summary>
        internal static string KeeAgentMenuItemToolTip {
            get {
                return ResourceManager.GetString("KeeAgentMenuItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load SS&amp;H Key.
        /// </summary>
        internal static string LoadKeyContextMenuItem {
            get {
                return ResourceManager.GetString("LoadKeyContextMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load SS&amp;H Key and Open URL.
        /// </summary>
        internal static string LoadKeyOpenUrlContextMenuItem {
            get {
                return ResourceManager.GetString("LoadKeyOpenUrlContextMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load SS&amp;H Keys.
        /// </summary>
        internal static string LoadKeysContextMenuItem {
            get {
                return ResourceManager.GetString("LoadKeysContextMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH key &apos;{0}&apos; was used by {1}..
        /// </summary>
        internal static string NotifyKeyFetched {
            get {
                return ResourceManager.GetString("NotifyKeyFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to another application.
        /// </summary>
        internal static string NotifyKeyFetchedUnknownApplication {
            get {
                return ResourceManager.GetString("NotifyKeyFetchedUnknownApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeeAgent is now locked.
        /// </summary>
        internal static string NotifyLocked {
            get {
                return ResourceManager.GetString("NotifyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeeAgent is now unlocked.
        /// </summary>
        internal static string NotifyUnlocked {
            get {
                return ResourceManager.GetString("NotifyUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string OptionAgentModeAgent {
            get {
                return ResourceManager.GetString("OptionAgentModeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string OptionAgentModeAuto {
            get {
                return ResourceManager.GetString("OptionAgentModeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string OptionAgentModeClient {
            get {
                return ResourceManager.GetString("OptionAgentModeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always require user confirmation when a client program requests to use a key.
        /// </summary>
        internal static string OptionAlwaysConfirm {
            get {
                return ResourceManager.GetString("OptionAlwaysConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore entries with missing external key files when automatically loading keys.
        /// </summary>
        internal static string OptionIgnoreMissingExternalKeyFiles {
            get {
                return ResourceManager.GetString("OptionIgnoreMissingExternalKeyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug logging.
        /// </summary>
        internal static string OptionLoggingEnabled {
            get {
                return ResourceManager.GetString("OptionLoggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification whenever a key is used by a client program.
        /// </summary>
        internal static string OptionShowBalloon {
            get {
                return ResourceManager.GetString("OptionShowBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string OptionsMenuItem {
            get {
                return ResourceManager.GetString("OptionsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock all databases when a client sends a request.
        /// </summary>
        internal static string OptionUnlockOnActivity {
            get {
                return ResourceManager.GetString("OptionUnlockOnActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show key selection dialog when a client program requests a list of all keys.
        /// </summary>
        internal static string OptionUserPicksKeyOnRequestIdentities {
            get {
                return ResourceManager.GetString("OptionUserPicksKeyOnRequestIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable agent for Windows OpenSSH (experimental).
        /// </summary>
        internal static string OptionUseWindowsOpenSshPipe {
            get {
                return ResourceManager.GetString("OptionUseWindowsOpenSshPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeeAgent is Locked.
        /// </summary>
        internal static string StatusLocked {
            get {
                return ResourceManager.GetString("StatusLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeeAgent is Unlocked.
        /// </summary>
        internal static string StatusUnlocked {
            get {
                return ResourceManager.GetString("StatusUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Agent Mode.
        /// </summary>
        internal static string TitleSuffixAgentMode {
            get {
                return ResourceManager.GetString("TitleSuffixAgentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Client Mode.
        /// </summary>
        internal static string TitleSuffixClientMode {
            get {
                return ResourceManager.GetString("TitleSuffixClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Algorithm.
        /// </summary>
        internal static string UnknownAlgorithm {
            get {
                return ResourceManager.GetString("UnknownAlgorithm", resourceCulture);
            }
        }
    }
}
