// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace KeeAgent {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translatable {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translatable() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KeeAgent.Translatable", typeof(Translatable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UnknownAlgorithm {
            get {
                return ResourceManager.GetString("UnknownAlgorithm", resourceCulture);
            }
        }
        
        internal static string OptionAgentModeAuto {
            get {
                return ResourceManager.GetString("OptionAgentModeAuto", resourceCulture);
            }
        }
        
        internal static string ErrUnknown {
            get {
                return ResourceManager.GetString("ErrUnknown", resourceCulture);
            }
        }
        
        internal static string KeeAgentMenuItemToolTip {
            get {
                return ResourceManager.GetString("KeeAgentMenuItemToolTip", resourceCulture);
            }
        }
        
        internal static string NotifyKeyFetched {
            get {
                return ResourceManager.GetString("NotifyKeyFetched", resourceCulture);
            }
        }
        
        internal static string OptionAgentModeAgent {
            get {
                return ResourceManager.GetString("OptionAgentModeAgent", resourceCulture);
            }
        }
        
        internal static string ErrParsingKey {
            get {
                return ResourceManager.GetString("ErrParsingKey", resourceCulture);
            }
        }
        
        internal static string OptionsMenuItem {
            get {
                return ResourceManager.GetString("OptionsMenuItem", resourceCulture);
            }
        }
        
        internal static string OptionAlwaysConfirm {
            get {
                return ResourceManager.GetString("OptionAlwaysConfirm", resourceCulture);
            }
        }
        
        internal static string ErrPpkFileException {
            get {
                return ResourceManager.GetString("ErrPpkFileException", resourceCulture);
            }
        }
        
        internal static string StatusUnlocked {
            get {
                return ResourceManager.GetString("StatusUnlocked", resourceCulture);
            }
        }
        
        internal static string ConfirmKeyFetch {
            get {
                return ResourceManager.GetString("ConfirmKeyFetch", resourceCulture);
            }
        }
        
        internal static string TitleSuffixClientMode {
            get {
                return ResourceManager.GetString("TitleSuffixClientMode", resourceCulture);
            }
        }
        
        internal static string OptionLoggingEnabled {
            get {
                return ResourceManager.GetString("OptionLoggingEnabled", resourceCulture);
            }
        }
        
        internal static string StatusLocked {
            get {
                return ResourceManager.GetString("StatusLocked", resourceCulture);
            }
        }
        
        internal static string AddToKeeAgentContextMenuItem {
            get {
                return ResourceManager.GetString("AddToKeeAgentContextMenuItem", resourceCulture);
            }
        }
        
        internal static string TitleSuffixAgentMode {
            get {
                return ResourceManager.GetString("TitleSuffixAgentMode", resourceCulture);
            }
        }
        
        internal static string NotifyUnlocked {
            get {
                return ResourceManager.GetString("NotifyUnlocked", resourceCulture);
            }
        }
        
        internal static string ButtonLock {
            get {
                return ResourceManager.GetString("ButtonLock", resourceCulture);
            }
        }
        
        internal static string OptionUnlockOnActivity {
            get {
                return ResourceManager.GetString("OptionUnlockOnActivity", resourceCulture);
            }
        }
        
        internal static string KeeAgent {
            get {
                return ResourceManager.GetString("KeeAgent", resourceCulture);
            }
        }
        
        internal static string OptionShowBalloon {
            get {
                return ResourceManager.GetString("OptionShowBalloon", resourceCulture);
            }
        }
        
        internal static string ErrPageantRunning {
            get {
                return ResourceManager.GetString("ErrPageantRunning", resourceCulture);
            }
        }
        
        internal static string OptionAgentModeClient {
            get {
                return ResourceManager.GetString("OptionAgentModeClient", resourceCulture);
            }
        }
        
        internal static string ButtonUnlock {
            get {
                return ResourceManager.GetString("ButtonUnlock", resourceCulture);
            }
        }
        
        internal static string NotifyLocked {
            get {
                return ResourceManager.GetString("NotifyLocked", resourceCulture);
            }
        }
    }
}
