//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeAgent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translatable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translatable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeAgent.Translatable", typeof(Translatable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another application is requesting SSH key &apos;{0}&apos;. Do you want to allow this?.
        /// </summary>
        internal static string ConfirmKeyFetch {
            get {
                return ResourceManager.GetString("ConfirmKeyFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pageant is already running. KeeAgent plugin will not be loaded..
        /// </summary>
        internal static string ErrPageantRunning {
            get {
                return ResourceManager.GetString("ErrPageantRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading key from entry &apos;{0}&apos; in group &apos;{1}&apos; in database &apos;{2}&apos;.
        /// </summary>
        internal static string ErrParsingKey {
            get {
                return ResourceManager.GetString("ErrParsingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &apos;{0}&apos; occured while parsing file &apos;{1}&apos;.
        /// </summary>
        internal static string ErrPpkFileException {
            get {
                return ResourceManager.GetString("ErrPpkFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string ErrUnknown {
            get {
                return ResourceManager.GetString("ErrUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeeAgent.
        /// </summary>
        internal static string KeeAgent {
            get {
                return ResourceManager.GetString("KeeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH key &apos;{0}&apos; was fetched by another application..
        /// </summary>
        internal static string NotifyKeyFetched {
            get {
                return ResourceManager.GetString("NotifyKeyFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string OptionsMenuItem {
            get {
                return ResourceManager.GetString("OptionsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage SSH Keys.
        /// </summary>
        internal static string ShowPuttyKeysMenuItem {
            get {
                return ResourceManager.GetString("ShowPuttyKeysMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage SSH Keys used by KeeAgent.
        /// </summary>
        internal static string ShowPuttyKeysMenuItemToolTip {
            get {
                return ResourceManager.GetString("ShowPuttyKeysMenuItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Algorithm.
        /// </summary>
        internal static string UnknownAlgorithm {
            get {
                return ResourceManager.GetString("UnknownAlgorithm", resourceCulture);
            }
        }
    }
}
