name: Build PLGX

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - run: nuget restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Build PLGX
      run: msbuild /property:Configuration=ReleasePlgx /t:build KeeAgent.sln

    - name: List PLGX
      run: ~\.nuget\packages\plgxtool\1.0.3\tools\PlgxTool.exe -l .\KeeAgent\bin\ReleasePlgx\KeeAgent.plgx

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: KeeAgent.plgx
        path: KeeAgent/bin/ReleasePlgx/KeeAgent.plgx
