name: Build DLL/PLGX

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install prerequisites
      run: |
        choco install keepass.install --version=2.50
        nuget restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build DLL
      run: msbuild /property:Configuration=ReleaseDll /t:build KeeAgent.sln

    - uses: actions/upload-artifact@v4
      with:
        name: KeeAgent.dll
        path: KeeAgent/bin/ReleaseDll/KeeAgent.dll

    - name: Build PLGX
      run: msbuild /property:Configuration=ReleasePlgx /t:build KeeAgent.sln

    - name: List PLGX
      run: ~\.nuget\packages\plgxtool\1.0.3\tools\PlgxTool.exe -l .\KeeAgent\bin\ReleasePlgx\KeeAgent.plgx

    - uses: actions/upload-artifact@v4
      with:
        name: KeeAgent.plgx
        path: KeeAgent/bin/ReleasePlgx/KeeAgent.plgx
