//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeAgent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeAgent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Help_png {
            get {
                object obj = ResourceManager.GetObject("Help_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon KeeAgent_icon {
            get {
                object obj = ResourceManager.GetObject("KeeAgent_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon KeeAgent_icon_mono {
            get {
                object obj = ResourceManager.GetObject("KeeAgent_icon_mono", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeeAgentIcon_png {
            get {
                object obj = ResourceManager.GetObject("KeeAgentIcon_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lechnology.com/KeeAgent+Beta+Options+and+Settings&amp;structure=KeeAgent+Beta#Database_Settings.
        /// </summary>
        internal static string WebHelpDatabaseSettings {
            get {
                return ResourceManager.GetString("WebHelpDatabaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lechnology.com/KeeAgent+Beta+Options+and+Settings&amp;structure=KeeAgent+Beta#Entry_Settings.
        /// </summary>
        internal static string WebHelpEntryOptions {
            get {
                return ResourceManager.GetString("WebHelpEntryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lechnology.com/KeeAgent+Beta+Manager&amp;structure=KeeAgent+Beta#EntryPicker.
        /// </summary>
        internal static string WebHelpEntryPicker {
            get {
                return ResourceManager.GetString("WebHelpEntryPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lechnology.com/KeeAgent+Beta+Options+and+Settings&amp;structure=KeeAgent+Beta#Global_Options.
        /// </summary>
        internal static string WebHelpGlobalOptions {
            get {
                return ResourceManager.GetString("WebHelpGlobalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lechnology.com/KeeAgent+Beta.
        /// </summary>
        internal static string WebHelpHome {
            get {
                return ResourceManager.GetString("WebHelpHome", resourceCulture);
            }
        }
    }
}
